%% Import data from text file.
% Script for importing data from the following text file:
%
%    G:\Spring2016\AMCS252\Project\ActualProject\code\RBFx64\RBFx64\Volume.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/09 14:31:46

%% Initialize variables.
filename = 'G:\Spring2016\AMCS252\Project\ActualProject\code\RBFx64\RBFx64\Volume.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
x = dataArray{:, 1};
y = dataArray{:, 2};
z = dataArray{:, 3};
f = dataArray{:, 4};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;


gridSz= length(x)/10/10;
x3d=reshape([x],gridSz,gridSz,gridSz,[]);
y3d=reshape([y],gridSz,gridSz,gridSz,[]);
z3d=reshape([z],gridSz,gridSz,gridSz,[]);
f3d=reshape([f],gridSz,gridSz,gridSz,[]);